apiVersion: batch/v1
kind: CronJob
metadata:
  name: statistics-client
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: statistics-client
            image: valerizab/time_request:v0.1
            volumeMounts:
            - name: data-volume
              mountPath: "/time_app/data"
          restartPolicy: OnFailure
          volumes:
          - name: data-volume
            hostPath:
              path: /data
              type: DirectoryOrCreate
